modLoader="kotlinforforge"
loaderVersion="[3,)"
license='MIT'

[[mods]]
modId="mctelemetrycore"
version="${file.jarVersion}"
displayName="MC Telemetry Core"
credits="The OpenTelemetry team and KotlinForForge"
authors="pixix4, ZincFox"
description='''
Monitor Minecraft with OpenTelemetry'''
[[dependencies.mctelemetrycore]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mctelemetrycore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19.3)"
    ordering="NONE"
    side="BOTH"
