name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      
      - name: Download dependencies
        run: |
          ./gradlew dependencies --no-daemon || true
          ./gradlew :common:dependencies --no-daemon || true
          ./gradlew :fabric:dependencies --no-daemon || true
          ./gradlew :neoforge:dependencies --no-daemon || true
      
      - name: Download OpenTelemetry agent
        run: ./gradlew downloadOTelAgent verifyOTelAgent --no-daemon || true
